### ISSUE TITLE
Steam level assertion bug

### ISSUE THREAD

**Issue by almatrass** [easton36/modern-passport-steam#5]
Steam level fetching in `fetchSteamLevel` causes assertion to fail on level 0 Steam accounts.

The assertion on line 33 of `steam-api.js` should be `playerLevel >= 0`, not just `playerLevel`.

Also, I think `fetchSteamLevel` should be disabled by default, just a suggestion.

**Comment by samplics** [comment]
Addressed in v1.1.1, thanks. Added better docs to README so it is clear that it is enabled by default if an API key is included
